#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: driver-did-sov
  newName: universalresolver/driver-did-sov
  newTag: latest

configMapGenerator:
- envs:
  - driver-did-sov.env
  name: driver-did-sov-env

resources:
- deployment.yml
- service.yml
