#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: uni-resolver-web
  newName: universalresolver/uni-resolver-web
  newTag: v0.4.0-8390e7a

configMapGenerator:
- files:
  - config.json
  name: uni-resolver-web-config
- files:
  - run-uni-resolver-web.sh
  name: uni-resolver-web-run

resources:
- deployment.yml
- service.yml
